version: '3.8'

services:
  lecture-ai-advanced:
    container_name: lecture-ai-advanced
    init: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8080:8080   # TensorBoard
      - 8888:8888   # Jupyter Notebook
    environment:
      - no_proxy="127.0.0.1,localhost"
      - NO_PROXY="127.0.0.1,localhost"
    env_file:
      - .env
      - path: local.env
        required: false
    volumes:
      - ..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
